apiVersion: v1
appVersion: 0.2.0
description: A chart for the pull sizer
name: pull-sizer
version: 0.2.0
home: https://github.com/helm/pull-sizer
maintainers:
- name: mattfarina
  email: matt@mattfarina.com
